### PR TITLE
fix: add active icon styling to link icon

### PR DESCRIPTION
**Pull request by arpitv96171**
Link bar link button container has active styling but the icon itself lacked the active styling. 
This PR adds the active styling to the link button in `EditLinkBar.tsx`

### CODE REVIEW

**Review by GuySerfaty — COMMENTED** [review]
Looks good to me, @17Amir17 please take a look and merge

**Review by GuySerfaty — CHANGES_REQUESTED** [review]
oh wait commit should follow the commit message convention
https://github.com/10play/10tap-editor/blob/main/CONTRIBUTING.md#commit-message-convention

**Comment by 17Amir17** [comment]
@arpitv96171 Thanks for the pr!

As @GuySerfaty mentioned you just need to change the commit message to something like `fix: active icon styling on link icon`

**Comment by arpitv96171** [comment]
@GuySerfaty will changing the PR title work? Or should I create another PR or add another commit with new commit message?

**Comment by 17Amir17** [comment]
@arpitv96171 you can rebase and force push with a new message - we cannot merge without these in the commit message
Opening a new pr with the correct commit message will work too

**Comment by arpitv96171** [comment]
new PR: #172

**Pull request closed without merging**
