### PR TITLE
Make Utils into TentapUtils

### PR DESCRIPTION
**Pull request by fahrulalwan**
Following upon the issue mentioned in #149 , this is the name i intend to change.

### CODE REVIEW

**Comment by 17Amir17** [comment]
Hey! Thanks for the pr
Can you update the commit to be `fix: rename Utils -> TentapUtils` it's required for us to merge this, see https://github.com/10play/10tap-editor/blob/main/CONTRIBUTING.md

**Comment by fahrulalwan** [comment]
hi @17Amir17 , please review the updated commit

**Review by 17Amir17 — APPROVED** [review]
Tested new and old arch LGTM

**Comment by fahrulalwan** [comment]
thanks! when the update will be released?

**Comment by 17Amir17** [comment]
Should already be out on `0.5.9`

**Comment by fahrulalwan** [comment]
https://github.com/10play/10tap-editor/releases/tag/v0.5.9

i thought `0.5.9` already released

**Comment by GuySerfaty** [comment]
@fahrulalwan should fix on 0.5.10

**Pull request merged**
